### ISSUE TITLE
do we really need the 'isFirefoxOS' flag?

### ISSUE THREAD

**Issue by sole** [mozilla/node-firefox-find-devices#3]
I tested connecting both a Firefox OS and an Android device, both with ADB debugging enabled. `adb devices` lists both of them:

```
List of devices attached
3739ce99    device
059f04960a226926    device
```

I then ran a simple test with this module to list detected devices. Only the Firefox OS device was returned, as you're filtering by that on the final output:

```
[ { id: '3739ce99', type: 'device', isFirefoxOS: true } ]
```

The `isFirefoxOs` flag in the output is confusing me, specially because as an advanced developer I ran `adb devices` to make sure that the Android phone was detected, so it makes the module look weird-is it it is not working properly? why do I have that flag if I can't get other things other than Firefox OS devices? etc

**Comment by tofumatt** [comment]
Finding a non-Firefox OS but Android device running Firefox eventually could be a possibility, right?

But, agreed, since it only finds Firefox OS devices we should probably strip that flag in our output, it’s weird and gives an expectation that non-Firefox OS devices would ever get returned right now, which isn’t the case. (Right?)

-tofumatt

On 23 March 2015 at 14:47:36, sole (notifications@github.com) wrote:

I tested connecting both a Firefox OS and an Android device, both with ADB debugging enabled. adb devices lists both of them:

List of devices attached
3739ce99 device
059f04960a226926 device

I then ran a simple test with this module to list detected devices. Only the Firefox OS device was returned, as you're filtering by that on the final output:

[ { id: '3739ce99', type: 'device', isFirefoxOS: true } ]

The isFirefoxOs flag in the output is confusing me, specially because as an advanced developer I ran adb devices to make sure that the Android phone was detected, so it makes the module look weird-is it it is not working properly? why do I have that flag if I can't get other things other than Firefox OS devices? etc

**Comment by lmorchard** [comment]
Yeah, ports forwarded from Firefox for Android is why. But, we can strip it out until / unless we want to support that.

And also now that I think about it, `adb devices` won't show that anyway... so we'll never support that in find-devices. So... derp.
